image:
  - Visual Studio 2019
before_build:
- cmd: >-
    git submodule update --init --recursive

    cmake -H. -B./build -G "Visual Studio 16 2019" -D GLOOMY_DEBUG:BOOL=TRUE
build:
  project: build/gloomy_learnopengl.sln
  parallel: true